<?php
/**
 * @file
 * Message FOS user to user messaging bridge for FOSMessage library.
 */

/**
 * Implements hook_requirements().
 */
function message_fos_requirements($phase) {
    $requirements = [];
    if ($phase == 'runtime') {
        if (!class_exists('FOS\Message\Repository')) {
            $requirements['fosmessage_library'] = [
                'value' => 'Message FOS',
                'description' => t('Message FOS requires the friendsofsymfony/message library.'),
                'severity' => REQUIREMENT_ERROR,
            ];
        }
    }

    return $requirements;
}

/**
 * Implements hook_entity_type_alter.
 *
 * Change the User entity class to our extended Person class.
 */
function message_fos_entity_type_alter(array &$entity_types) {
    $entity_types['user']->setClass('Drupal\message_fos\Driver\Driver\Model\Person');
}